{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0f0230d2-f6aa-4898-b31d-eee173a56b5c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 29 Listing files to process.\n",
      "\n",
      "--- Individual File Row Counts (Before Concatenation) ---\n",
      "CRMLSListing202401.csv: 27,454 rows\n",
      "CRMLSListing202402.csv: 27,447 rows\n",
      "CRMLSListing202403.csv: 32,282 rows\n",
      "CRMLSListing202404.csv: 36,503 rows\n",
      "CRMLSListing202405.csv: 38,796 rows\n",
      "CRMLSListing202406.csv: 35,893 rows\n",
      "CRMLSListing202407.csv: 36,340 rows\n",
      "CRMLSListing202408.csv: 35,305 rows\n",
      "CRMLSListing202409.csv: 34,625 rows\n",
      "CRMLSListing202410.csv: 34,730 rows\n",
      "CRMLSListing202411.csv: 25,128 rows\n",
      "CRMLSListing202412.csv: 19,417 rows\n",
      "CRMLSListing202501.csv: 37,469 rows\n",
      "CRMLSListing202502.csv: 33,983 rows\n",
      "CRMLSListing202503.csv: 38,492 rows\n",
      "CRMLSListing202504.csv: 40,187 rows\n",
      "CRMLSListing202505.csv: 40,271 rows\n",
      "CRMLSListing202506.csv: 26,399 rows\n",
      "CRMLSListing202507.csv: 27,345 rows\n",
      "CRMLSListing202508.csv: 25,210 rows\n",
      "CRMLSListing202509.csv: 26,923 rows\n",
      "CRMLSListing202510.csv: 27,586 rows\n",
      "CRMLSListing202511.csv: 20,677 rows\n",
      "CRMLSListing202512.csv: 18,773 rows\n",
      "CRMLSListing202601.csv: 35,302 rows\n",
      "CRMLSListing202602.csv: 32,884 rows\n",
      "CRMLSListing202603.csv: 39,153 rows\n",
      "CRMLSListing202604.csv: 39,020 rows\n",
      "CRMLSListing202605.csv: 36,580 rows\n",
      "\n",
      "--- Final Summary Logs ---\n",
      "Total Rows Combined (Before Filter): 930,174 rows\n",
      "Total Rows Kept (After Residential Filter): 591,890 rows\n",
      "\n",
      "Done! Master file saved successfully to: /Users/samikshadubey/Downloads/IDX Code/Files/listings.csv\n"
     ]
    }
   ],
   "source": [
    "# Week 1 - Monthly Dataset Aggregation\n",
    "# IDX Exchange Data Analyst Internship\n",
    "# Author: Samiksha Dubey\n",
    "# Date: 2026-06-24\n",
    "#\n",
    "# This script:\n",
    "# 1. Loads all available monthly CRMLSListing files\n",
    "# 2. Concatenates them into two combined datasets\n",
    "# 3. Filters contactenated files to PropertyType == 'Residential' only\n",
    "# 4. Saves the filtered datasets as listings.csv \n",
    "\n",
    "# Sold files start from 202401 (January, 2024) till 202605 (May 2026)\n",
    "\n",
    "\n",
    "import glob\n",
    "import os\n",
    "import pandas as pd\n",
    "\n",
    "# 1. Directory Setup\n",
    "data_folder = \"/Users/samikshadubey/Downloads/IDX Code/Files\"\n",
    "listing_files = sorted(glob.glob(os.path.join(data_folder, \"CRMLSListing*.csv\")))\n",
    "\n",
    "print(f\"Found {len(listing_files)} Listing files to process.\\n\")\n",
    "print(\"--- Individual File Row Counts (Before Concatenation) ---\")\n",
    "\n",
    "# 2. Read files and track individual row counts\n",
    "listing_dfs = []\n",
    "for file_path in listing_files:\n",
    "    df = pd.read_csv(file_path, low_memory=False)\n",
    "    print(f\"{os.path.basename(file_path)}: {len(df):,} rows\")\n",
    "    listing_dfs.append(df)\n",
    "\n",
    "# 3. Concatenate and Filter\n",
    "listings_master = pd.concat(listing_dfs, ignore_index=True)\n",
    "listings_residential = listings_master[\n",
    "    listings_master[\"PropertyType\"] == \"Residential\"\n",
    "]\n",
    "\n",
    "# 4. Final Validation Logs\n",
    "print(\"\\n--- Final Summary Logs ---\")\n",
    "print(f\"Total Rows Combined (Before Filter): {len(listings_master):,} rows\")\n",
    "print(f\"Total Rows Kept (After Residential Filter): {len(listings_residential):,} rows\")\n",
    "\n",
    "# 5. Export\n",
    "output_path = os.path.join(data_folder, \"listings.csv\")\n",
    "listings_residential.to_csv(output_path, index=False)\n",
    "print(f\"\\nDone! Master file saved successfully to: {output_path}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "18a2b1be-1d69-4f90-93fd-eeed929f4933",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
